import type { LevelSpec } from "../types/LevelSpec";

export const levels = [
  {
    id: 1,
    title: "The Envelope at the Kancelaria",
    shortTitle: "Kancelaria Envelope",
    settingSummary: "Maria's kancelaria on her birthday morning, where one sealed envelope waits on her desk.",
    briefingText: "Inside the envelope are a brass key, a tram ticket, and the first warning of the case.",
    platformerFocus: "Safe platforms, route-awakening handoff, one collectible, and two forgiving checkpoints.",
    platformerMechanicFamily: "intro traversal",
    exhibitName: "The Sealed Envelope",
    puzzleType: "case-mosaic",
    emotionalReveal: "Maria notices what others miss.",
    targetDurationSeconds: { min: 75, max: 105 },
    difficulty: "intro",
    designRole: "tutorial"
  },
  {
    id: 2,
    title: "The Tram of Deadlines",
    shortTitle: "Deadline Tram",
    settingSummary: "The tram route from the envelope winds through Warsaw's warm moving lights.",
    briefingText: "The ticket needs order before the golden validator will reveal the next mark.",
    platformerFocus: "Forgiving moving tram platforms, stamp route, hidden wall, and Vistula handoff.",
    platformerMechanicFamily: "moving platforms",
    exhibitName: "The Golden Stamp",
    puzzleType: "case-timeline",
    emotionalReveal: "Maria carries responsibility with grace.",
    targetDurationSeconds: { min: 105, max: 135 },
    difficulty: "gentle",
    designRole: "early mastery"
  },
  {
    id: 3,
    title: "The Rebuilt Street",
    shortTitle: "Rebuilt Street",
    settingSummary: "The stamped route ends at a rebuilt street with one brick hiding a keyhole.",
    briefingText: "The stamped route must be connected through the keyhole and hidden wall to reveal the river sign.",
    platformerFocus: "Rebuilding platforms or appearing/disappearing safe paths.",
    platformerMechanicFamily: "rebuilding platforms",
    exhibitName: "The Red Brick",
    puzzleType: "route-tile-puzzle",
    emotionalReveal: "Strong things are built patiently, piece by piece.",
    targetDurationSeconds: { min: 90, max: 120 },
    difficulty: "gentle",
    designRole: "timing layer / first richer emotional level"
  },
  {
    id: 4,
    title: "The Vistula Deposition",
    shortTitle: "Vistula Deposition",
    settingSummary: "The repaired wall image points Maria toward the Vistula and a nervous witness.",
    briefingText: "The witness note says the heart was not stolen; it was left willingly.",
    platformerFocus: "Riverbank traversal, drifting papers, witness note handoff, and archive-code transition.",
    platformerMechanicFamily: "collection gates",
    exhibitName: "The Witness Note",
    puzzleType: "deposition-order",
    emotionalReveal: "Maria hears the quiet version of truth.",
    targetDurationSeconds: { min: 90, max: 120 },
    difficulty: "moderate",
    designRole: "first thinking level"
  },
  {
    id: 5,
    title: "The Archive of Tiny Details",
    shortTitle: "Tiny Details",
    settingSummary: "The witness note opens an archive drawer marked by a quiet reference code.",
    briefingText: "A correction in the margin may change the whole charge.",
    platformerFocus: "Switches, keys, doors, and simple route choice.",
    platformerMechanicFamily: "keys and doors",
    exhibitName: "The Marginal Note",
    puzzleType: "case-file-sorting",
    emotionalReveal: "Small details become evidence when someone truly loves you.",
    targetDurationSeconds: { min: 105, max: 135 },
    difficulty: "moderate",
    designRole: "recombination"
  },
  {
    id: 6,
    title: "The Courthouse of Echoes",
    shortTitle: "Courthouse Echoes",
    settingSummary: "The marginal correction releases a silver key to the Courthouse of Echoes.",
    briefingText: "The key opens nothing until Maria asks the question that reaches Trust, follows the lantern path, and rises to the blue-ribbon pages.",
    platformerFocus: "Choice doors, lantern reveal, forgiving vertical elevators, and the blue-ribbon handoff.",
    platformerMechanicFamily: "choice navigation / lantern elevators",
    exhibitName: "The Silver Key",
    puzzleType: "trust-light-path",
    emotionalReveal: "Real love is proven by choosing each other again.",
    targetDurationSeconds: { min: 120, max: 150 },
    difficulty: "moderate",
    designRole: "late-middle trust ascent"
  },
  {
    id: 7,
    title: "The Garden of Quiet Evidence",
    shortTitle: "Quiet Garden",
    settingSummary: "Behind the Trust door, a lantern leads Maria into a quiet garden.",
    briefingText: "The lantern path waits patiently, lighting one answer after another.",
    platformerFocus: "Calm exploration, lantern switches, and low-risk traversal.",
    platformerMechanicFamily: "lantern switches",
    exhibitName: "The Lantern",
    puzzleType: "lantern-sequence",
    emotionalReveal: "Maria is warmth, calm, and home.",
    targetDurationSeconds: { min: 75, max: 90 },
    difficulty: "gentle",
    designRole: "emotional reset"
  },
  {
    id: 8,
    title: "The Tower of Arguments",
    shortTitle: "Argument Tower",
    settingSummary: "The garden path ends at argument pages tied with a blue ribbon.",
    briefingText: "The ribbon asks Maria to build an argument strong enough to release the letter.",
    platformerFocus: "Vertical ascent, elevators, and timing with safe hazard cycles.",
    platformerMechanicFamily: "vertical timing",
    exhibitName: "The Blue Ribbon",
    puzzleType: "argument-tower",
    emotionalReveal: "The strongest argument is not spoken once. It is lived.",
    targetDurationSeconds: { min: 100, max: 130 },
    difficulty: "confident",
    designRole: "hazard puzzle"
  },
  {
    id: 9,
    title: "The Rooftops Before the Verdict",
    shortTitle: "Before the Verdict",
    settingSummary: "The unfinished letter carries Maria above Warsaw, where every prior clue glows below.",
    briefingText: "The sentence can finish only when the earlier clues find their meanings.",
    platformerFocus: "Rooftop synthesis, clue memory markers, forgiving floating lifts, and final court approach.",
    platformerMechanicFamily: "ceremonial synthesis / floating ascent",
    exhibitName: "The Unfinished Letter",
    puzzleType: "case-constellation",
    emotionalReveal: "Every clue points to the same conclusion: Maria is deeply loved for who she is.",
    targetDurationSeconds: { min: 120, max: 150 },
    difficulty: "finale",
    designRole: "ceremonial finale traversal"
  },
  {
    id: 10,
    title: "The Court of the Heart",
    shortTitle: "Court of the Heart",
    settingSummary: "The completed letter opens the Court of the Heart, built from every clue before it.",
    briefingText: "Maria aligns the final seal and lets the verdict open.",
    platformerFocus: "Celebratory traversal across the previous clues, easier than Level 9.",
    platformerMechanicFamily: "celebration reprise",
    exhibitName: "The Heart Seal",
    puzzleType: "final-verdict-assembly",
    emotionalReveal: "The seal is ready for the verdict.",
    targetDurationSeconds: { min: 120, max: 150 },
    difficulty: "finale",
    designRole: "finale"
  }
] as const satisfies readonly LevelSpec[];

export function getLevelById(levelId: number): LevelSpec | undefined {
  return levels.find((level) => level.id === levelId);
}
